### ISSUE TITLE
issue about segment in build_pretrain_dataset.py

### ISSUE THREAD

**Issue by kelvinleen** [google-research/electra#20]
first_segment = []
    second_segment = []
    for sentence in self._current_sentences:
      # the sentence goes to the first segment if (1) the first segment is
      # empty, (2) the sentence doesn't put the first segment over length or
      # (3) 50% of the time when it does put the first segment over length
      if (first_segment or
          len(first_segment) + len(sentence) < first_segment_target_length or
          (second_segment and
           len(first_segment) < first_segment_target_length and
           random.random() < 0.5)):
        first_segment += sentence
      else:
        second_segment += sentence

i have two question about above snippet code:
1. does the above code in “if“ branch should be "not first_segment" and "not second_segment"？ 
2. it seems there would be chances like this: suppose sentences are A,B,C, and A,C in first_segment but B in second_segment?   dose the sentence order not matter?

**Comment by clarkkev** [comment]
Thank you for pointing out the issue, this is a bug! It should be fixed [fixed](https://github.com/google-research/electra/commit/1ed085288ed265898cdb5deaf55bd56da252af80) now.

**Comment by kelvinleen** [comment]
hey， what about the second question？ i still cannot understand why this situation is allowed. shouldn't sentences in first_segment are all before those in second_segment? 

A,B,C three sentences, B goes to second_segment when probability> 0.5, then len(A)+len(C) < first_segment_target_length would make C goes to first_segment again. 
which makes A,C in first_segment but B in second_segment.
